name: Main

env:
  EXTENSION_FILE_NAME: aws-sso-account-filter-web-extension

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.vscode/**'
      - 'LICENSE'

jobs:
  build:
    name: Build
    timeout-minutes: 3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Volta Node Version
        id: volta_version
        run: echo "node_version=$(jq -r .volta.node package.json)" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.volta_version.outputs.node_version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:coverage

      - name: Upload coverage
        uses: coverallsapp/github-action@v2

      - name: Create release tag
        id: tag
        run: echo "release_tag=$(date +"%Y.%-m.%-d.%-H%-M")" >> $GITHUB_OUTPUT

      - name: Write release tag to files
        run: |
          echo Writing release tag to package.json
          jq '.version |= "${{ steps.tag.outputs.release_tag }}"' package.json | tee tmp-package.json && mv tmp-package.json package.json
          echo Writing release tag to public/manifest.json
          jq '.version |= "${{ steps.tag.outputs.release_tag }}"' public/manifest.json | tee public/tmp-manifest.json && mv public/tmp-manifest.json public/manifest.json

      - name: Build
        run: npm run build

      - name: Create Chrome dist directory
        run: |
          cp -r  ./dist/ ./chrome-dist/
          cd chrome-dist
          cat manifest.json | jq 'del(.browser_specific_settings)' > chrome-manifest.json && mv chrome-manifest.json manifest.json

      - name: Create Firefox dist directory
        run: cp -r  ./dist/ ./firefox-dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EXTENSION_FILE_NAME }}-v${{ steps.tag.outputs.release_tag }}
          path: dist/
          retention-days: 90
          if-no-files-found: error

      - name: Upload Chrome artifact
        uses: actions/upload-artifact@v3
        with:
          name: chrome-${{ env.EXTENSION_FILE_NAME }}-v${{ steps.tag.outputs.release_tag }}
          path: chrome-dist/
          retention-days: 90
          if-no-files-found: error

      - name: Upload Firefox artifact
        uses: actions/upload-artifact@v3
        with:
          name: firefox-${{ env.EXTENSION_FILE_NAME }}-v${{ steps.tag.outputs.release_tag }}
          path: firefox-dist/
          retention-days: 90
          if-no-files-found: error

      - name: Setup Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit ammended files with release tag
        run: |
          git status
          git commit --all --message "ðŸ¤– Release v${{ steps.tag.outputs.release_tag }}"
          git push

      - name: Compress dist for Firefox release
        run: |
          cd firefox-dist
          zip -r ../firefox-${{ env.EXTENSION_FILE_NAME }}-v${{ steps.tag.outputs.release_tag }}.zip .

      - name: Compress dist for Chrome release
        run: |
          cd chrome-dist
          zip -r ../chrome-${{ env.EXTENSION_FILE_NAME }}-v${{ steps.tag.outputs.release_tag }}.zip .

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.tag.outputs.release_tag }}
          files: |
            chrome-${{ env.EXTENSION_FILE_NAME }}-v${{ steps.tag.outputs.release_tag }}.zip
            firefox-${{ env.EXTENSION_FILE_NAME }}-v${{ steps.tag.outputs.release_tag }}.zip
          generate_release_notes: true
